GestionApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from GestionApp import views

urlpatterns = [
   path('admin/', admin.site.urls),
   path('',views.first_view, name='first_view' ),
   path('empleado/crear/',views.EmpleadoCreate.as_view(), name='crear-empleado' ),
   path('empleado/listar/',views.EmpleadoListView.as_view(), name='empleado-list' ),
   path('empleado/<int:pk>/eliminar/', views.EmpleadoDelete.as_view(), name='empleado-eliminar'),
   path('empleado/<int:pk>/modificar/', views.EmpleadoUpdate.as_view(), name='empleado-modificar'),
   path('empleado/<int:pk>/detalle/', views.EmpleadoDetailView.as_view(), name='empleado-detalle'),
   path('empleado/<int:pk>/detalle2/', views.empleado_detail2, name='empleado-detalle2'),
   path('gestion/listar/',views.GestionListView.as_view(), name='gestion-list' ),
   path('gestion/crear/',views.GestionCreate.as_view(), name='crear-gestion' ),
   path('accounts/', include('registration.backends.default.urls')),
   path('empleado/<str:pCedula>/buscar/',views.buscar_empleado, name='buscar-empleado' ),

]

GestionEmpleados/urls.py
from django.contrib import admin
from django.urls import path, include
from GestionApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion/',include('GestionApp.urls') ),
    path('accounts/', include('registration.backends.default.urls')),

]

GestionApp/models.py
from django.db import models
from datetime import datetime 
from django.dispatch import receiver
from django.urls import reverse
from django.db.models.signals import post_delete

# Create your models here.

class Empleado(models.Model):
    cedula = models.CharField(max_length=100)
    genero = models.CharField(max_length=100)
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.CharField(max_length=100)
    estado = models.BooleanField(default=False)
    edad = models.IntegerField()
    foto = models.ImageField(upload_to='photos/')

    def __str__(self):
        return self.nombres

    def get_absolute_url(self):
        return reverse('empleado-list')

@receiver(post_delete, sender=Empleado)
def foto_delete(sender, instance, **kwargs):
    """ Borra los ficheros de las fotos que se eliminan. """
    instance.foto.delete(False)

class Gestion(models.Model):
     empleado = models.ForeignKey('Empleado', on_delete=models.PROTECT)
     horaEntrada = models.DateTimeField(default=datetime.now,blank=True)
     horaSalida = models.DateTimeField(default=datetime.now,blank=True)

     def get_absolute_url(self):
        return reverse('empleado-list')
     
     def __str__(self):
        return self.empleado.nombres
    
    

GestionApp/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.dispatch import receiver
from django.db.models.signals import post_delete
from GestionApp.models import Empleado, Gestion
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.shortcuts import render
from datetime import datetime, timedelta

from django.views.generic.edit import UpdateView, CreateView, DeleteView
# Create your views here.
def first_view(request):
    return render(request, 'base.html') 

class EmpleadoListView(ListView):
    model = Empleado

class EmpleadoDetailView(DetailView):
    model = Empleado

    
class EmpleadoUpdate(UpdateView):
	model = Empleado
	fields = '__all__'

class EmpleadoCreate(CreateView):
	model = Empleado
	fields = '__all__'

class GestionCreate(CreateView):
    model = Gestion
    fields='__all__'

class EmpleadoDelete(DeleteView):
    model = Empleado
    success_url = reverse_lazy('empleado-list')

class GestionListView(ListView):
    model = Gestion

def empleado_detail2(request, pk):
    empleado = Empleado.objects.get(id=pk)
    context = {'object': empleado}
    return render(request, 'GestionApp/empleado_detail2.html', context)

def buscar_empleado(request, pCedula):
   empleado1=Empleado.objects.filter(cedula=pCedula).first()
   context = {'object': empleado1}
   gestion = Gestion(empleado=empleado1,horaEntrada=datetime.now,horaSalida=datetime.now)
   gestion.save()
   return render(request, 'GestionApp/gestion_form.html', context)

GestionApp/templates/GestionApp/buscar.html
{{object.nombres}}
{{object.horaEntrada}}

GestionApp/templates/GestionApp/empleado_confirm_delete.html
{% extends 'base.html' %}

{% block maincontent %}
    <form action="" method="post">{% csrf_token %}
        <h3>Eliminar a "{{ object }}"?</h3>
        <input class="btn btn-success" type="submit" value="Confirmar" />
        <a type="button" class="btn btn-danger" href="{% url 'empleado-list' %}">Cancel</a>
    </form>
{% endblock maincontent %}

GestionApp/templates/GestionApp/empleado_detail.html
{% extends 'base.html' %}

{% load static %}

{% block section %}


<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


        <div class="container" style="width: 95%; margin-right: 20%" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{object.nombres}}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="{% static object.foto.url %}" class="img-circle img-responsive"> </div>
                
                <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                        <tr>
                            <td>Cédula:</td>
                            <td>{{object.cedula}}</td>
                          </tr>
                      <tr>
                        <td>Nombres:</td>
                        <td>{{object.nombres}}</td>
                      </tr>
                      <tr>
                        <td>Apellidos:</td>
                        <td>{{object.apellidos}}</td>
                      </tr>
                      <tr>
                        <td>Edad</td>
                        <td>{{object.edad}}</td>
                      </tr>
                   
                         <tr>
                             <tr>
                        <td>Género:</td>
                        <td>{{object.genero}}</td>
                      </tr>
                        <tr>
                        <td>Télefono</td>
                        <td>{{object.telefono}}</td>
                      </tr>
                      <tr>
                        <td>Estado:</td>
                        {% if object.estado %}
                        <td>Activo</a></td>
                        {%else%}
                        <td>Inactivo</td>
                        {%endif%}
               
            
    
                      </tr>
                           
                      </tr>
                     
                    </tbody>
                  </table>
                  
                  <a href="{% url 'empleado-detalle2' object.id %}" class="btn btn-primary">Ver Historial de asistencia</a>
              
        
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a  data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="{% url 'empleado-modificar' object.id %}" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a  href="{% url 'empleado-eliminar' object.id %}" data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                       
                          </span>
                    </div>
            
          </div>
        </div>
      </div>
    </div>

    <style type="text/css">
    .user-row {
    margin-bottom: 14px;
}

.user-row:last-child {
    margin-bottom: 0;
}

.dropdown-user {
    margin: 13px 0;
    padding: 5px;
    height: 100%;
}

.dropdown-user:hover {
    cursor: pointer;
}

.table-user-information > tbody > tr {
    border-top: 1px solid rgb(221, 221, 221);
}

.table-user-information > tbody > tr:first-child {
    border-top: 0;
}


.table-user-information > tbody > tr > td {
    border-top: 0;
}
.toppad
{margin-top:20px;
}
    </style>

{% endblock section %}

{% block maincontent %}

{% endblock maincontent %} 

GestionApp/templates/GestionApp/empleado_detail2.html
{% extends 'base.html' %}

{% load static %}

{% block section %}


<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


        <div class="container" style="width: 95%; margin-right: 20%" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{object.nombres}}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="{% static object.foto.url %}" class="img-circle img-responsive"> </div>
                
                <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9 "> 
                    <table class="table">
                        <thead>
                          <tr>
               
                            <th scope="col">Ingreso</th>
                            <th scope="col">Salida</th>
                          
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                              {% for gestion in object.gestion_set.all %}
                   
                         
                            <td>{{gestion.horaEntrada}}</td>
                            <td>{{gestion.horaSalida}}</td>
              

                          </tr>
                          {%endfor%}
                        </tbody>
                        </table>
               
        
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a  data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="{% url 'empleado-modificar' object.id %}" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a  href="{% url 'empleado-eliminar' object.id %}" data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                       
                          </span>
                    </div>
            
          </div>
        </div>
      </div>
    </div>

    <style type="text/css">
    .user-row {
    margin-bottom: 14px;
}

.user-row:last-child {
    margin-bottom: 0;
}

.dropdown-user {
    margin: 13px 0;
    padding: 5px;
    height: 100%;
}

.dropdown-user:hover {
    cursor: pointer;
}

.table-user-information > tbody > tr {
    border-top: 1px solid rgb(221, 221, 221);
}

.table-user-information > tbody > tr:first-child {
    border-top: 0;
}


.table-user-information > tbody > tr > td {
    border-top: 0;
}
.toppad
{margin-top:20px;
}
    </style>

{% endblock section %}

{% block maincontent %}

{% endblock maincontent %} 

GestionApp/templates/GestionApp/empleado_form.html
{% extends 'base.html' %}
{% block maincontent %}
{% block form %}
    <form method="post" enctype=multipart/form-data>
        {% csrf_token %}
       <div class="form-group">
                    <label for="exampleInputEmail1">{{ form.as_p }}</label>
        
      
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a class='btn' href="{% url 'empleado-list' %}">Cancelar</a>
    </form>

    {% endblock %}
{% endblock maincontent%}

GestionApp/templates/GestionApp/empleado_list.html
{% extends 'base.html' %}
{% load static %}
<div class="container">
    {% block section %}

    <section class="content-header">
         <h1>Empleados <br>
    <small>Gestionar empleados</small>
</h1>
<br>
{% if perms.empleado.add_empleado %}

<a href="{% url 'crear-empleado'%}"><img src="https://cdn3.iconfinder.com/data/icons/ios-edge-glyph-1/25/Add-Users-512.png"  style="width:60px;height:60px">
</a>


{% endif %}

</section>
    <br>
{% endblock section %}
{% block maincontent %}
<div class="from-controler" style="width: 95%; ">
    {% for p in object_list  %}
    <ul class="list-group">
        <li class="list-group-item"><h4>{{p}}</h4> 
            <hr>
            
            <img src="{% static p.foto.url %}" style="width:90px;height:90px" />
            <hr>
            <a href="{% url 'empleado-detalle' p.id %}"><h4>Ver Detalles</h4></a> 
            
     
        </li>
    </ul>
    {% endfor %}
</div>

{% endblock maincontent %}

GestionApp/templates/GestionApp/gestion_form.html
{% extends 'base.html' %}
{% block maincontent %}
{% block form %}
    <form method="post" enctype=multipart/form-data>
        {% csrf_token %}
       <div class="form-group">
                {{ form.as_p }}
            {{form.horaEntrada}}
      
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a class='btn' href="{% url 'empleado-list' %}">Cancelar</a>
    </form>
    {{object.nombres}}
{{object.horaEntrada}}

    {% endblock %}
{% endblock maincontent%}

GestionApp/templates/GestionApp/gestion_list.html
{% extends 'base.html' %}
{% load static %}

    {% block section %}

    
{% endblock section %}
{% block maincontent %}
<div class="from-controler" style="width: 95%; ">

    <ul class="list-group">

            <hr>
            <ul>
            {% for p in object_list %}
            <li>{{ p.horaEntrada }}</li>
              {% endfor %}
    </ul>
            <hr>
       
            
     
        </li>
    </ul>

</div>

{% endblock maincontent %}

GestionApp/templates/GestionApp/registro_empleado.html
hola!!

GestionApp/templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

GestionApp/templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<b>ALB</b>{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<b>Gestión</b>{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}/accounts{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                        {%else%}
                        <div class="pull-right">
                                <a href="auth_login"class="btn btn-default btn-lg active" role="button">Iniciar Sesión</a>
                            </div>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

GestionApp/templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

            {% block nav_links %}
            <li>
                 {% if user.is_authenticated %}
                <a href="{% url "empleado-list" %}">
                    <i class="fa fa-users"></i> <span>Gestionar Empleados</span>
                </a>
                {% endif %}
            </li>
            
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>

GestionApp/templates/base.html
{% extends 'adminlte/base.html' %}
{% block title %}Album{% endblock %}
{% block content %}
    <div class="container">
        {% block section %}
            <h1>Bienvenid@!</h1>
        {% endblock section %}
    </div>

    <div class="container">
        {% block maincontent %}
        <a href="{% url 'auth_login'%}">Iniciar Sesión</a>

        <input type="text"  id="pCedula" value="id_cedula">
        <a href="{% url 'buscar-empleado' 1234%}">buscar!</a>
    <!----> 
    <button type="submit"></button>

        {% endblock maincontent %}
    </div>
</form>

{% endblock %}